version: '3.9'

services:
  app:
    image: go-fiber-mongo-hrms
    container_name: app
    restart: always
    ports:
      - "${APP_HOST_PORT}:${APP_PORT}"
    env_file:
      - .env
    depends_on:
      - "mongodb"
  mongodb:
    image: mongo:5.0
    container_name: ${DB_HOST}
    ports:
      - "${DB_HOST_PORT}:${DB_PORT}"
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
      - MONGO_INITDB_DATABASE=${DB_NAME}